### ISSUE TITLE
Detect modified/incomplete downloaded files

### ISSUE THREAD

**Issue by vkchan** [icloud-photos-downloader/icloud_photos_downloader#116]
If a picture/video is modified in iCloud, will the downloader be able to pick up the changes and re-download it? Does it run a checksum or compare file size?

If the downloader was interrupted, it appears that the partially downloaded file is still left in the folder, when I re-run the downloader, will it be able to detect the file was incomplete and re-download it?

I know the downloader will skip a file if it already existing, but not sure if it's only checking the filename, or it also detect any modifications in the file/incomplete downloads?

Thanks!

**Comment by ndbroadbent** [comment]
Hi @vkchan, unfortunately we only check to see if the file already exists. We don't currently look at a checksum / size / modified date, but that would be a big improvement.

The iCloud API does provide a checksum and size for each file. I'm not too sure how the checksum is calculated, but I think it might be a base64 encoded SHA-1 hash. I think we can just use the filesize check, because hash calculation would be too slow for every file. But it might be good to verify the checksum after the file has been downloaded, and retry if it doesn't match.

It might also be good to save a "manifest.yml" file in the photos directory, which would look something like:

```
"C3A554F5-D919-4D55-8D3B-E8D826001990":
  mediaType: "photo"
  mimeType: "image/jpg"
  filename: "Photos/2018/08/21/IMG_7505-original.JPG"
  fileChecksum: "Ae06wjwh7bS6IIbyKjIEMFtf4x/E"
  size: 858940
  lastModified: 1543851058
```

iCloud has a unique record ID for each photo, so would make sense to use those instead of checking for generated filenames.

Unfortunately I don't have a lot of time to work on this script right now (and I don't even use it anymore.) Hopefully some other people will be able to help with contributing new features like this.

**Comment by vkchan** [comment]
Thanks for the quick response! It makes a lot of sense, and I hope this feature would be available soon in the future, as there hasn't a good solution for sync iCloud photos to a local drive in an organized way.

**Comment by dvgeek** [comment]
This would be a great enhancement!

**Comment by AndreyNikiforov** [comment]
Added PR for checking size in addition to names: https://github.com/ndbroadbent/icloud_photos_downloader/pull/160

**Comment by AndreyNikiforov** [comment]
@vkchan do you still experience the issue with latest version (1.6.1)?

**Comment by AndreyNikiforov** [comment]
Closing as fixed
