### ISSUE TITLE
Skip existing photos

### ISSUE THREAD

**Issue by Suncatcher** [icloud-photos-downloader/icloud_photos_downloader#130]
Very often having a bad internet connection download session is interrupted and I have to download all again. Having hundreds of photos is not fun as I often don't know the exact photos it had interrupted on and I should download all *again*. It would be nice to implement either of these 2 options:

1. Skip existing photos in the folder. I.e. if the photo with the same name exists in folder do **not** start downloading and go to next photo. Now I see it makes this check after downloading.
2. Have the switch to start download from Nth photo if the filename of existing photo is known.

**Comment by Naich** [comment]
check file-metadata takes more time than downloading the file content.  from the code it seems skipping is working.

https://github.com/ndbroadbent/icloud_photos_downloader/blob/798c598df312774902f55423e72a569c01a78a18/icloudpd/base.py#L440

**Comment by AndreyNikiforov** [comment]
This https://github.com/ndbroadbent/icloud_photos_downloader/pull/159 helps with broken downloads. It will re-download partial files and will never leave partial assets.

**Comment by Suncatcher** [comment]
Partial files is good but does it remember which file was partial and from which file to start the next download? Otherwise it is useless, and after completing partial file it will start from the beginning of collection.

**Comment by AndreyNikiforov** [comment]
https://github.com/ndbroadbent/icloud_photos_downloader/pull/159 downloads asset to temp file (original + .part extension) and renames/moves temp file to the final name once downloading completes. If download was interrupted, next session will re-download whole temp file again. 

That approach solves the problem of incomplete files due to broken connection, but does not save traffic like smart downloaders do.

Tool supports checking for existing files today and does not download them if they are the same. I submitted another PR https://github.com/ndbroadbent/icloud_photos_downloader/pull/160 to enhance this check process to use file size in addition to file name.

**Comment by AndreyNikiforov** [comment]
@Suncatcher do you still issues with re-downloading? What version of the icloudpd are you using?
