### ISSUE TITLE
Shared library downloading

### ISSUE THREAD

**Issue by carlnorum** [icloud-photos-downloader/icloud_photos_downloader#153]
Feature request: allow downloading of images from shared libraries. When I use `--list-albums` I get a bunch of stuff, but none of the shared libraries are in the list.

**Comment by robertomano24** [comment]
Would love this feature too.

**Comment by phenomeus** [comment]
that would be so great to incorporate that into my magic mirror

**Comment by didusee** [comment]
would like to second that request. :)

**Comment by ccb056** [comment]
I'm also looking for this functionality

**Comment by gregbert42** [comment]
me too - just came to see if i could find out how to do that.

**Comment by jon-small** [comment]
Running in a container. Unlike iCloud for Windows, this is awesome software - thanks! Would love to have this feature as well.

**Comment by wsc96** [comment]
This would be great. Any progress on this?

**Comment by aluncoppack** [comment]
@menkej I cam across this script (and others that are similar) for accessing shared libraries. Would this help? https://gist.github.com/javiribera/3c1cbb0f2831d42d83bb2473188e3fac

**Comment by adamcandy** [comment]
I looked at this project a while ago -- when it hosted on @ndbroadbent's GitHub account -- and in the end went for a different approach to manage photos, mainly since it could not handle shared albums.  Still, it looks really interesting, and I'd take a look again if I move to depending on iCloud photos more.

For shared albums I use [VMannello/iCloud-PS-Download.git](https://github.com/VMannello/iCloud-PS-Download) which works really well.  There is a caveat, in that you need to enable web-sharing in the shared album options and then use the provided URL.  I recommend taking a look at this as a suggestion of how to get this working for shared albums.  I have an extended version which reads a config file for multiple shared albums and additionally uploads a backup to Google Photos using `google_auth_oauthlib` and `google` libraries.

**Comment by editwentyone** [comment]
@adamcandy could you help out with this python script? 

all I get is and after googling around I can't get my head around it 
`/usr/bin/python: No module named iCloudBd`

**Comment by epheterson** [comment]
I think this is actually tracking shared _albums_ and not shared _libraries_. In iOS 16 a new feature called shared libraries was released which behaves differently. Going to file a new ticket.

**Comment by sinnerlolqt** [comment]
Unsubscribe not working lost 2fa to other account please remove me Sent from Mail for Windows From: Adam CandySent: Thursday, March 31, 2022 8:45 AMTo: icloud-photos-downloader/icloud_photos_downloaderCc: SubscribedSubject: Re: [icloud-photos-downloader/icloud_photos_downloader] Shared library downloading (#153) I looked at this project a while ago -- when it hosted on @ndbroadbent's GitHub account -- and in the end went for a different approach to manage photos, mainly since it could not handle shared albums. Still, it looks really interesting, and I'd take a look again if I move to depending on iCloud photos more.For shared albums I use VMannello/iCloud-PS-Download.git which works really well. There is a caveat, in that you need to enable web-sharing in the shared album options and then use the provided URL. I recommend taking a look at this as a suggestion of how to get this working for shared albums. I have an extended version which reads a config file for multiple shared albums and additionally uploads a backup to Google Photos using google_auth_oauthlib and google libraries.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by AndreyNikiforov** [comment]
#688
