### ISSUE TITLE
Didn't progress anymore after password input section appear

### ISSUE THREAD

**Issue by Felsaspalt** [icloud-photos-downloader/icloud_photos_downloader#158]
I booted PowerShell or Command Prompt on Win10 and typed like below, and didnt progress when i try to input my password.
Does anyone know this problem is belonging to me or iCloud Server?

PS C:\Users\MyPC> icloudpd
iCloud username/email: myemail@gmail.com
2020-08-01 14:17:04 DEBUG    Authenticating...
iCloud Password:

**Comment by metahnetoutage** [comment]
Because you are not reading nor following instructions which are in of
themselves not very good.

Use \ for your path as "C:\\A\\B" why \\ and not \ because it tells python
to treat \ as symbol and not escape sequence like \t for tab.
So you type this:

Note if your directory is on an external drive you need to get that path
from explorer.

icloudpd -d \pathtoyourdirectory

Enter your username
Enter your password

Congrats!

**Comment by menkej** [comment]
@Felsaspalt does the description of @metahnetoutage solve your issue?

**Comment by menkej** [comment]
Mandatory command line options should be really clear and lead to program termination/user information if something is missing.

**Comment by AndreyNikiforov** [comment]
Required parameters are fixed in 1.6.2. Closing. @Felsaspalt pls reopen if latest version of icloudpd did not solve your issue.
