### ISSUE TITLE
Inconsistent result of test_until_found

### ISSUE THREAD

**Issue by AndreyNikiforov** [icloud-photos-downloader/icloud_photos_downloader#188]
test_until_found behaves inconsistently. Need to understand the pattern and fix it.

See #186 as an example

**Comment by menkej** [comment]
I have no Idea what is happening here. It works like a charm on my local Mac installation with python 3.8. The Actions on GitHub run on Linux. This should not really make a difference... And also different versions in the matrix test keep failing. Maybe we should revert to just one test-version again?

**Comment by AndreyNikiforov** [comment]
> Maybe we should revert to just one test-version again?

If we claim that we support 3.6+ then we should test for these versions. We need to figure out why test is failing and fix it.

On Windows platform, for example, I suspected that creating large files takes a while and test fails with timeout.

**Comment by menkej** [comment]
I have configured a 5 min limit for the tests right now. Do you think it is too low? AND: the Action on Github is not failing because of timeout, as the whole action fails in < 5 mins...

Funny enough I have (sometimes) other tests failing on my local installation:
```
test_download_photos_and_set_exif
test_download_photos_and_set_exif_exceptions
test_invalid_creation_year
```
Usually failing because of a timeout. They run for ages, if I would not use a timeout... Do the tests run ok on your installation? I think I'll set up a linux box tonight to run the tests in a different environment as well. Maybe I can find out something else...

I have no problem with using a newer python-version. Most current distros come with 3.8+ anyways today. This would also enable to use newer 3rd party libs. Even though python 3.6 is still receiving security patches till end of 2021 and python 3.7 till end of 2023... newer version (3.8/3.9) still receive also bugfixes, not only security... (taken from [here...](https://www.python.org/downloads/))

**Comment by AndreyNikiforov** [comment]
I am using `docker buildx build .` and it was relatively stable. Tests on Windows are flaky. Increasing timeouts is a last resort IMO, we need to figure out what causing issues and fix that.

**Comment by menkej** [comment]
finally the tests run smoothly on my Mac! Good job @AndreyNikiforov !
