### ISSUE TITLE
Documentation on how to create a test case

### ISSUE THREAD

**Issue by menkej** [icloud-photos-downloader/icloud_photos_downloader#202]
We aim to have 100% test-coverage, which is a very good thing. As the structure of the test cases is not very straight forward (to me and probably others), I'd like to have some kind of how-to that explains the steps to create a test case. Especially:

- How to create a Cassette
  - what is it good for after all
  - anonymization
  - best practices
- test sczenarios
  - positive/negative tests
  - test before development
- to be continued

Maybe we start a wiki page, or add this to CONTRIBUTING.md. What do you think? @ndbroadbent maybe you already have something at hand?

**Comment by AndreyNikiforov** [comment]
VCR/cassette use requires icloud account with desired state setup. Discussed at some extent in #182 

Good approach to simplify testing would be to break the app in layers. Requesting data from Apple servers will be one layer and processing data another. Then vcr module would be needed for former, while later can be unit tested by passing python data structures.

Separate data processing layer will also allow testing on function output as python data structures, rater than on log/stdout content. That will make it easier to validate all output content rather than check for inclusion of certain strings in log as it is done today in many tests (==missing validation on the order and the rest of the output).

Refactoring can be started as part of any ticket IMO and I was planning to do first cut in #196

**Comment by menkej** [comment]
I agree with the refactoring. I was basically talking about a little recipe/checklist/best-practices on "how to test icloudpd" that we could use for us but also hand it to pull request submitters that forget about adding the tests and don't know where to start. Maybe that was not clear in my initial posting.

**Comment by menkej** [comment]
I started adding infos to the CONTRIBUTING.md as test cases where again an issue in a pull request. Then I thought about adding it to a wiki page. I'm not sure which way would be better... What you you think, @AndreyNikiforov and @ndbroadbent ? First draft is here: https://github.com/icloud-photos-downloader/icloud_photos_downloader/wiki/How-to-write-a-unit-test

**Comment by AndreyNikiforov** [comment]
I have mixed feeling about wikis as they do not have versioning and change control as .md files. It is much better to have wikis than nothing though -- thanks a lot for putting this together!

**Comment by menkej** [comment]
I'm more than happy to put it back into CONTRIBUTING.md (still have it there locally). The wiki is nothing else then a git repo itself. History can be found here: https://github.com/icloud-photos-downloader/icloud_photos_downloader/wiki/How-to-write-a-unit-test/_history

Anyways: Do you have anything to add/change for that article, or is it ok as a first shot?

**Comment by AndreyNikiforov** [comment]
It looks good! Minor typo: "start addind tests"

Missing review process for wikis...

**Comment by menkej** [comment]
> Missing review process for wikis...

True. But instantly editable. ;-) I got it. I'll move it/leave it in CONTRIBUTING.md
