### ISSUE TITLE
Specifying user on command line still prompts for passwords 

### ISSUE THREAD

**Issue by carylewis** [icloud-photos-downloader/icloud_photos_downloader#292]
## Summary
I want to be able to run icloudpd from a cron job, and don't want to have to specify the password on the command line. I used the icloud keyring command as indicated in the documentation, and the password is being stored correctly, however when I specify my username via the -u command, I am still prompted for my password.

If I don't specify the username via the -u option, then I am only prompted for the username, and then the program appears to retrieve the password from the keyring.

Is it possible to run icloudpd, without user intervention,  without having to specify the password on the command line?

**Comment by menkej** [comment]
Hi Cary,
that is strange. I tried the following:

1. `python3 icloudpd.py --list-albums`: Prompt for username, no prompt for password, albums are listed.
2. `python3 icloudpd.py --list-albums -u mymail@bla.com`: No prompt for username or password, albums are listed.

So it works as expected. Can you add a little more info what you're calling?

**Comment by bobhavlin** [comment]
Same problem here.  

If I run the following from a terminal:
`icloudpd -a Favorites --folder-structure {:%Y/%m} -d /home/ubuntu/icloud_favorites/Favorites  --recent 200 --username user@email.com 
`
works as expected.  If the same command runs from cron:
```
2021-04-05 05:24:22 DEBUG    Authenticating...
iCloud Password: 
/usr/lib/python3.8/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Aborted!

```

**Comment by jakublipinski** [comment]
I had the same issue. It seems the `keyring` have some issues when run from `crontab`. I switched to `luanchd` and `launchctl` and it works for me now.

**Comment by ashleycawley** [comment]
I think I might be running into the same issue; I'm on Zorin OS (Ubuntu based) and I've put together my own shell script using the documentation, I'm using absolute paths for everything (python bin, icloudpd.py, my script/cron etc), I can run the shell script on the terminal and it completes successfully without being prompted for any username or password (as its saved in the keyring) but if I copy the same command and put it into a cron, it runs the script but seemingly quits out almost instantly, I believe it might be a auth issue because when I redirect the output to a log it just shows:
2021-11-20 16:14:01 DEBUG    Authenticating...      
iCloud Password:

**Comment by ashleycawley** [comment]
I've tried two different methods: having the python command and options in a shell script and even trying the python + all options in the crontab, but both result in the same as I mentioned above. If I run the shell script from the shell it works beautifully with no auth prompts.

Unfortunately because this now wont work for me at all in an automated fashion via cron I'm at a complete loss and it looks like this solution wont work for me :cry: such a shame, through testing etc. I just took it for granted the cron / auth aspect would work reliably so I could automate this but it seems not.

**Comment by boredazfcuk** [comment]
Looks like your cron command can’t find the keyring file (likely a permissions issue, or running as different user), so it’s prompting you to enter your password. It can’t do this when running from cron because it’s running in a session which has no terminal.

Either that, or it’s because the crown command doesn’t have an environment so doesn’t know where home is all and stuff like that.

**Comment by carylewis** [comment]
Why not do a cron job that ssh’s into the account? Hopefully the environment will be same as an interactive terminal session.

**Comment by ashleycawley** [comment]
@boredazfcuk I even tried sudo -u username with it.

@carylewis you nailed it! :grin: What a beautifully simple hack and **_it works!_** Thank you.

So ignoring the timings of my cron, my previous cron line of:
`/home/acawley/Scripts/my_icloud_sync/my_icloud_sync.sh`
Would not work (despite the script working when executed manually), but when changed to this:
`ssh -o StrictHostKeyChecking=no acawley@localhost /home/acawley/Scripts/my_icloud_sync/my_icloud_sync.sh`
It worked a treat :partying_face: 

In order for it to work in an automated fashion I obviously had to setup a key-pair and put my public key in my authorized_keys file, but after that all good. **So this could be a viable work-around** for anyone else suffering with this keyring/cron/environment issue, thanks @carylewis !

**Comment by boredazfcuk** [comment]
> @boredazfcuk I even tried sudo -u username with it.

you need -p to preserve the environment too with sudo at a guess.

Sounds like your running cron as root though, rather than as your user account. The /etc/crontab file is where you should be launching it from though, as that lets you specify the user account to run the command as.

**Comment by ashleycawley** [comment]
I wasn't running it as root, I can assure you of that, I was editing the crontab as my user.

**Comment by carylewis** [comment]
I’m so glad it worked. Glad to have helped. Thanks for the shout out. Take care.

**Comment by boredazfcuk** [comment]
It must be due to the environment differences then.

I’d just export the environment as your user, then import it at the start of your script.
