### ISSUE TITLE
PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason')

### ISSUE THREAD

**Issue by far5man** [icloud-photos-downloader/icloud_photos_downloader#404]
账号密码明明是对的，但是还是提示这个。

PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason')

**Comment by menkej** [comment]
sorry, I can't read Chinese (if it is...). Can you elaborate a little on how you end up with this error, otherwise I can't reproduce or fix anything. Thanks.

**Comment by boredazfcuk** [comment]
@menkej Not sure if you've seen, but I've had a few people mention they have problems logging in from mainland China. It seems some users accounts need to authenticate against icloud.com.cn instead of icloud.com.

I've added a variable to my container which just switches out icloud.com for icloud.com.cn in pyicloud_ipd/base.py and this works. I'd guess that this is the problem that OP is seeing. That his e-mail/password combo is incorrect as it's authenticating against the wrong server.

**Comment by menkej** [comment]
Could be the case here, too. Can you imagine a way to detect this automatically? I'd like to avoid adding a commandline option for this...

**Comment by boredazfcuk** [comment]
Unfortunately not as it doesn’t affect all users… I was wondering if it’s just a migration process that Apple China has started, but is still underway. Maybe , at some point in the future, all Chinese accounts will have to authenticate against icloud.com.cn.

I did think about IP GeoIP lookups to detect if the user is located within China, but this isn’t going to be 100% accurate.

Being a long way from China myself, I’ve no real way to investigate.

**Comment by menkej** [comment]
> Being a long way from China myself, I’ve no real way to investigate.

same for me...

**Comment by menkej** [comment]
Duplicate to #392
