### ISSUE TITLE
Telegram notifications and _ in apple ID

### ISSUE THREAD

**Issue by doma2345** [icloud-photos-downloader/icloud_photos_downloader#409]
## Overview
Application wont start when there is an '_' in the apple ID as it fails to send the start up notification to telegram.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Add an _ to the apple id
2. Make sure you have telegram notifications turned on
3. start application

## Expected Behavior
It should send start up notification and continue

## Actual Behavior
It errors out on the start up notification and stops

**Comment by boredazfcuk** [comment]
This has been created in the wrong repo. You need to raise it here: https://github.com/boredazfcuk/docker-icloudpd/issues

However, this issue was raised, and fixed, a couple of years ago: https://github.com/boredazfcuk/docker-icloudpd/issues/27

It's possible something upstream has changed, so please post a full log (with identifiable information removed).

**Comment by menkej** [comment]
Any idea why we cant use the "Transfer issue" feature in github to move those issues directly to your docker project, @boredazfcuk ? I can't select docker-icloudpd when I try to transfer...

**Comment by boredazfcuk** [comment]
>You can only transfer issues between repositories owned by the same user or organization account.

https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

I guess this is probably it... I looked at creating a workflow, so that I could automatically update my container's version number when you guys updated your code, That would then trigger a container rebuild over at Dockerhub. Everything I read said that you can't monitor repos owned by different users. Guessed something similar would apply to repo issues.

**Comment by boredazfcuk** [comment]
Can do. I'm not sure how much more valuable I can be though. I've been trying to learn Python so can help out with the project (and also shift my career path from sysadmin to devops), but have only managed about 30 hours training time since Christmas.

So, I didn't actually manage that through GitHub's workflows, but I have actually implemented it for a different container I use. It's codebase is updated fairly frequently, so I just have a nightly cron job running which checks the GitHub API for the code's "updated_at" time stamp, and if it's newer than what is in my dockerfile, I write the new time stamp to the dockerfile and then rebuild the container. It's not as slick as workflow triggered updates, but it works well enough for me.

**Comment by S474N** [comment]
And what about add Telegram support also for this project?

**Comment by Jonnypleasehelp** [comment]
Delete telegram stuff

**Comment by S474N** [comment]
> Delete telegram stuff

!?!?!

**Comment by AndreyNikiforov** [comment]
> And what about add Telegram support also for this project?

My current focus is around core functionality -- downloading iCloud assets. I would love to see notifications to be extensible, possibly by externalizing that functionality. From that perspective adding doc to show how to process results and, say, send Telegram notifications can be helpful.

**Comment by AndreyNikiforov** [comment]
no plans for telegram. closing
