### ISSUE TITLE
Restartable Copy

### ISSUE THREAD

**Issue by gfody** [icloud-photos-downloader/icloud_photos_downloader#660]
## Summary
If a Copy fails for any reason, the ability to restart where it left off would save a lot of time spent skipping existing files. One way to implement this feature would be to add two new abilities:
- ability to indicate a mode of operation where the internal state of the Copy command would be serialized and emitted upon failure (default something like ~.icloudpd-errorstate)
- ability to resume a failed Copy command with the provided state information (default to reading the default file if it's there)

..with these abilities and these defaults, just retrying the last command would resume making progress much sooner.

## Context
I'm downloading ~35k files totaling ~250gb and half way through it failed with "Connection aborted". Upon retrying it takes ~5min to check and skip existing files before it resumes downloading again. Based on the frequency of "Connection aborted" failures and subsequent recovery times it could potentially take forever to finish downloading by just retrying in a loop.

**Comment by AndreyNikiforov** [comment]
@gfody thanks for suggestion. How long does it take to download 250G of your photos? How many errors did you get (or error vs downloaded size if you are not done yet)? I am trying to get some sense of the overall gain (for the time) you expect to get.

If the gain worth implementation/investment, one workaround/simple approach may be to download photos in predefined order (e.g. by date added) and provide cli parameter to filter by that property.

**Comment by gfody** [comment]
in the end I only restarted 5 times and got everything downloaded in ~12h

**Comment by AndreyNikiforov** [comment]
> in the end I only restarted 5 times and got everything downloaded in ~12h

Thanks for stats. The feature would have saved you 25min or ~3% of your time. 

I think special feature to support fast continuation is not warranted here as it adds complexity and does not give 100% guarantee of success (e.g. if some files were skipped, one will have to run full check anyways). Filter by date may be helpful though and it may be used by other use cases.

**Comment by gfody** [comment]
> Thanks for stats. The feature would have saved you 25min or ~3% of your time.

The recovery takes longer as the Copy progresses (as there are more files to check). The last few restarts took ~20min each. I ran a Copy just now that skipped 100% of the files and it took 20:54
``` 
100%|##########| 35711/35711 [20:54<00:00, 28.47it/s]
```
(cpu: 3800X, storage: Sabrent Rocket 8TB NVMe)

Presumably this would be a bigger problem for someone with a much larger iCloud or a much worse "Connection aborted" rate.

> I think special feature to support fast continuation is not warranted here as it adds complexity and does not give 100% guarantee of success (e.g. if some files were skipped, one will have to run full check anyways).

Regarding complexity and reliability, I suspect emitting and restoring state can be done more simply and reliably than implementing Copy with date filters (due to the corner cases described in #466). Consider the case where a long Copy is running and some files that have been copied are moved on iCloud - if the Copy fails then upon restarting you might download duplicates, whereas Restartable Copy should yield the same result as if the Copy had not failed.

Thank you for this project btw it has totally rescued me from iCloud for Windows (which fails to sync after several weeks!)

**Comment by AndreyNikiforov** [comment]
Thanks for sharing your thoughts.

> The recovery takes longer as the Copy progresses (as there are more files to check). The last few restarts took ~20min each. I ran a Copy just now that skipped 100% of the files and it took 20:54

Yes, I see your point. There is an inevitable cost of rechecking all files at every synch. There is a benefit, which I mentioned before: resiliency -- if files are skipped (==gaps in local file set), they will be restored at next run. For the first time sync with errors that extra cost you'll always have to pay with current version. For ongoing periodic sync (`--watch-with-interval`) extra minutes of checking for files in the collection becomes relevant (I am checking my `icloudpd` instances for multiple accounts once in a few days and reliability plus notification on errors are significantly more important than extra minutes for that use case).

> 
> Presumably this would be a bigger problem for someone with a much larger iCloud or a much worse "Connection aborted" rate.
> 

Watch mode today does not handle these situations well (==stops the program). I think there is an opportunity to stop watching for changes only when non-retriable error happens.

> > I think special feature to support fast continuation is not warranted here as it adds complexity and does not give 100% guarantee of success (e.g. if some files were skipped, one will have to run full check anyways).
> 
> Regarding complexity and reliability, I suspect emitting and restoring state can be done more simply and reliably than implementing Copy with date filters (due to the corner cases described in #466). Consider the case where a long Copy is running and some files that have been copied are moved on iCloud - if the Copy fails then upon restarting you might download duplicates, whereas Restartable Copy should yield the same result as if the Copy had not failed.
> 

I saw a fork that implemented persisting of the derived state (photos are primary state) into local sql db. Check it out if you think that functionality is valuable to you. My current view is that storing derived state not worth the impact (complexity of code and its maintenance, complexity of app setup and its maintenance/upgrades, reduced resiliency due to potential desynchronization between persisted states etc). Separate storage of the derived state is used in image processing apps and it worth benefits there.

> Thank you for this project btw it has totally rescued me from iCloud for Windows (which fails to sync after several weeks!)

That is how many ppl came to this project (I did).
