### ISSUE TITLE
Shared object error on setup

### ISSUE THREAD

**Issue by BLLiNNK** [icloud-photos-downloader/icloud_photos_downloader#732]
## Overview
I am attempting to setup but getting the below error when running first test 

`/volume1/homes/xxx/icloudpd/lib/python3.8/site-packages/icloud/icloud: error while loading shared libraries: libz.so.1: failed to map segment from shared object`

## Steps to Reproduce
1. install package, pip and wheel 
2. Run ` icloud —username xx@xx.com`

## Expected Behavior
From the guide, I believe I should be prompted for password

## Actual Behavior
`/volume1/homes/xxx/icloudpd/lib/python3.8/site-packages/icloud/icloud: error while loading shared libraries: libz.so.1: failed to map segment from shared object`

## Context
Synology DSM 7.2.1-69057 Update 3  and Python 3.8

**Comment by genegoykhman** [comment]
I'm trying to set up icloudpd for the first time and ran into this problem as well. Not sure how to proceed.

**Comment by michaelmolino** [comment]
This sounds like an environment issue to me.  It might be easier to build the docker container and run it from there.  That said, this project is currently broken so you're going to get an authentication issue anyway.  See #729 .

**Comment by yorkday** [comment]
I had the same issue, and found it was due to a lack of TMP directory in my environment variables (running on Synology).  I didn't have this issue previously on Synology, so not sure if it was recently introduced problem with icloudpd, or my Synology.  After fixing my temporary folder issue, I hit another issue, but that's unrelated.

Article: https://stackoverflow.com/questions/57796839/docker-compose-error-while-loading-shared-libraries-libz-so-1-failed-to-map-s

Steps I took were (change the path for your environment):
```
root@DiskStation:/usr/local/bin/scripts/backups_icloud# icloudpd
/usr/lib/python3.8/site-packages/icloudpd/icloudpd: error while loading shared libraries: libz.so.1: failed to map segment from shared object
root@DiskStation:/usr/local/bin/scripts/backups_icloud# mkdir tmp
root@DiskStation:/usr/local/bin/scripts/backups_icloud# export TMP=/usr/local/bin/scripts/backups_icloud/tmp
root@DiskStation:/usr/local/bin/scripts/backups_icloud# icloudpd
[26321] Error loading Python lib '/usr/local/bin/scripts/backups_icloud/tmp/_MEIhzdftS/libpython3.12.so.1.0': dlopen: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by /usr/local/bin/scripts/backups_icloud/tmp/_MEIhzdftS/libpython3.12.so.1.0)
```

**Comment by yorkday** [comment]
On further reading, it looks like it could be because the /tmp directory does not have execute privileges, so your choices are either to remount your current /tmp directory with these permissions, or create a separate tmp folder and export that to your path.

Investigating my Synology shows the /tmp path is 'noexec', meaning icloudpd couldn't execute something from the /tmp directory.

```
root@DiskStation:/tmp# mount | grep -i /tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noexec)
```
