### ISSUE TITLE
impossible to generate a two-factor token

### ISSUE THREAD

**Issue by biGdada** [icloud-photos-downloader/icloud_photos_downloader#752]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )

my two-factor token has expired. there is no option to choose authentication mechanism (sms/otp), it just asks for a code but the code does not appear on my devices.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
attempt to login

## Expected Behavior
the program is supposed to ask what kind of login is it (sms/otp) and proceed accordingly

## Actual Behavior

`2023-12-27 10:43:25 DEBUG    Authenticating...
2023-12-27 10:43:26 INFO     Two-step/two-factor authentication is required (2fa)
Please enter two-factor authentication code:
`

## Context
[NOTE]: # ( Give us any additional information you may have. )

**Comment by biGdada** [comment]
additional info: 
deleting the relevant account files from ./pyicloud directory sort of solves the problem.
now the authentication message appears on my devices, but there is no option to login by sms

**Comment by scaraebeus** [comment]
I have the `scaraebeus/2fa_enhancements` branch which adds a switch to display trusted (SMS) devices to send a code to - but there is not a pull request for it yet as it's not fully tested.

Feel free to test it out if you want - if you pass the `--list-devices` option (along with the other minimum required options) and you don't already have a validated session, you should get a list of available SMS devices to send a code to (or can choose to just enter the code that was auto-sent to the device).

I can clean up the tests and verify test coverage if it works and submit an official pull request.

**Comment by Dylqn** [comment]
Hey @biGdada, this also happened to me running version 1.17.3.

Not sure if your situation is the same as mine, but I'll explain what I did in case it helps you or anyone else down the line.

Steps to reproduce:
- icloudpd command and flags were stored in an `.sh` file
- Ran script via terminal as usual (i.e. -- running `./icloudpd.sh`)

This script contained the following:
`icloudpd --directory /mnt/iCloud --username email@icloud.com --auto-delete --recent 10 --smtp-username email@gmail.com \
--smtp-password password_here --notification-email email@icloud.com --watch-with-interval 86400`

Resolution:
- I had to run the command "manually" rather than running it as a script.

Example:
Ran the following command via terminal:
`icloudpd --directory /mnt/iCloud --username email@icloud.com --auto-delete --recent 10 --watch-with-interval 86400`
- I removed all smtp entries when running this manually and I was prompted for my 2fa code without the expiration notice.
- This allowed me to continue and my photos started syncing to the directory specified.
- I immediately cancelled the process and ran my original script and was not prompted for my 2fa code.

**Comment by ThomasBalder** [comment]
I had the same issue in 1.17.3 for a few weeks now. I fixed it using @Dylqn method, but slightly different. From terminal I ran `/var/services/homes/tbalder/icloudpd-venv/bin/icloud --username "my@username" --llist` and weirdly enough now I did get a MFA prompt...
Perhaps it's a coincidence, maybe the MFA token got purged (don't know if that's a thing here), maybe it's something else. Hope this works for you too @biGdada (at least as a workaround).

**Comment by Dylqn** [comment]
As time passed, my iCloud account would want a new 2FA code. The script would fail to run again or notify the email I had for smtp. I just ended up removing all smpt flags from my script and the 2FA code is requested and I am able to pass it in successfully from a trusted device.

**Comment by AndreyNikiforov** [comment]
1.17.4 restored support for sending 2fa through SMS. However, I noticed that it is not consistent - was given that option for my accounts initially, but then disappeared. Current hypothesis is that `icloudpd` uses outdated/deprecated Apple apis for getting available SMS-capable devices on the account.

closing as fixed. getting better SMS support will be enhancement.
