### ISSUE TITLE
Totally New and need help

### ISSUE THREAD

**Issue by GreekCY** [icloud-photos-downloader/icloud_photos_downloader#757]
## Summary
I just downloaded icloudpd. I am totally new to this and my knowledge of command line is very basic. I am on a Mac using terminal. I have been trying to understand how to write the command but it is not working the way I want it.

## Context
I want to download the Albums of my iCloud and have them as such listed locally, eg. Album 1, Album 2, etc. Is this possible at all? The structure I keep getting is 2023 then 11, then 9 and so on.

The command I type is:
 % icloudpd -d /Users/me/iCloud_Photos -u me@email.com -p 123456 -a Videos    
The next issue is, if I have a folder named Album Videos it doesn not recognize the command: --album: album videos or --album album videos or -a album videos.
I get the message icloudpd <options> 
Try icloudpd -h 
but I don't seem to understand how to give the command

if I try to have various options together it never works, for example how do I write the command albums so and so and then keep the folder structure and then delete after download all in one command?

Next question is: 
I have a local server but not the iclould docker.
Whats is the command to transfer the files directly to the server? 
I have the same difficulty if it is an external HD.

TIA for any help that comes along.

**Comment by Vivvns** [comment]
Hey friend,

I ran into similar problems downloading photos into an external HD, here's how I addressed them:

### 1) Downloading Specific Albums "Videos":

For albums with spaces in their names, **enclose the album name in quotes**. For example, for an album named "Videos":

`icloudpd -d /Users/me/iCloud_Photos/Videos --username me@email.com --password 123456 --album "Videos"`

Repeat this for each album, changing the destination directory **(-d)** and the album name **(--album)** accordingly.

### 2) Combining Multiple Options in One Command:

If you want to download an album, keep a specific folder structure, and delete after download, your command might look like this:

`icloudpd -d /Users/me/iCloud_Photos/Videos --username me@email.com --password 123456 --album "Videos" --folder-structure "{:%Y/%m}" --delete-after-download`

### 3) Direct Download to Server/External HD: 

If the server or external HD is mounted and accessible like a local directory, you can directly specify its path in the icloudpd command. Here's what I used for my External HD:

`icloudpd -d /Volumes/External_HD/Photos --username me@email.com --password 123456 --album "Videos"`

Since I don't have a local server, I asked chatGPT for a way to transfer the downloaded files and was suggested to: 

_Use a file transfer command like rsync or scp to transfer them to your server. Example:_

`rsync -av /Users/me/iCloud_Photos/ user@server:/path/to/server/directory`

_Replace **user@server** with your server's username and address, and **/path/to/server/directory** with the destination directory on your server._

Icloudpd is a great tool to download icloud photos, so hope this helps!

**Comment by GreekCY** [comment]
Thank you so much and happy new year. I will give it a try and report back.

**Comment by GreekCY** [comment]
I tried what you advised and wow it worked very nicely. Thanks again!
