### ISSUE TITLE
iCloud Drive and Ubiquity support

### ISSUE THREAD

**Issue by CreativePR** [icloud-photos-downloader/icloud_photos_downloader#798]
## Summary
Add ability to list contents of iCloud Drive and download contents (with same functionality) as iCloud Photo library

## Context
Seems as if this should be able to be done.  If you can download the photo library, why not the iCloud drive library as well Ubiquity space.

**Comment by AndreyNikiforov** [comment]
> If you can download the photo library, why not the iCloud drive library as well Ubiquity space.

This project started because of the need to have photos downloaded locally for processing/management and Apple's own software did not provide that capability. What is the need for having a copy of iCloud drive and what options already exist? I am not familiar with Ubiquity service and assume same questions apply for that service too.
