### ISSUE TITLE
Windows 1.17.5 version detected as Trojan:Win32/Bearfoos.A!ml

### ISSUE THREAD

**Issue by CreativePR** [icloud-photos-downloader/icloud_photos_downloader#832]
In Windows version 1.17.5 - Windows Defender now detecting iCloudPD as Trojan:Win32/Bearfoos.A!ml

Previous versions did not have this issue.

**Comment by boredazfcuk** [comment]
Someone else seeing same issue:

https://superuser.com/questions/1416678/my-own-backup-program-was-detected-as-win32-bearfoos-aml-virus#1417342

**Comment by AndreyNikiforov** [comment]
tested with https://www.virustotal.com/gui/file/1df602c6413610c4ae4b92b7d652054a193458eeaee7127a1339d61a106a6e33/detection - looks like two other products detect viruses, but Windows Defender seems to be okay (I assume 'Microsoft" in the report is Windows Defender)...

As a workaround, I can suggest updating Windows Defender.

**Comment by CreativePR** [comment]
> tested with https://www.virustotal.com/gui/file/1df602c6413610c4ae4b92b7d652054a193458eeaee7127a1339d61a106a6e33/detection - looks like two other products detect viruses, but Windows Defender seems to be okay (I assume 'Microsoft" in the report is Windows Defender)...
> 
> 
> 
> As a workaround, I can suggest updating Windows Defender.

I'll check it out- thanks

**Comment by AndreyNikiforov** [comment]
@CreativePR has you solved the issue?

**Comment by Lheligh** [comment]
Same issue here - except Windows Defender marking the ZIP as "Trojan:Win32/Wacatac.H!ml" - for both v1.17.5 and the latest 1.18.x

Security Intelligence version is latest at 1.411.423.0

**Comment by AndreyNikiforov** [comment]
The tool that we use to package `icloudpd` [suggests](https://github.com/pyinstaller/pyinstaller/issues/5854) that false positive detection for trojans is because many trojans are using the same tool for packaging their apps. Reporting the issue as false positive to Win Defender authors or not using Win Defender at all were the two options suggested.

Closing as there is nothing `icloudpd` can do about that.
